name = "Unlimited Fabric"
author = "trollham"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "372da61d4ffe71f61a7c413e92ab53ed0beae928a939cd240c4b9ed6474fa7e0"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
