name = "Unlimited Fabric"
author = "trollham"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea7c2ee51eadd7ff079574d106eab27bfbcf49dc2f8c8503623b52ac8a86bf6c"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
