name = "Unlimited Fabric"
author = "trollham"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87674ee1dcaee641a57525d32ce1992b8f08f268d9ac5f055b4ff9ae9c53b2f9"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
