name = "Unlimited Fabric"
author = "trollham"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5bac86dd62f094742f12ff22f2dd1f774c2d5fe8886cfe3256fb802a8bde771"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
