name = "Unlimited Fabric"
author = "trollham"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51ae99d434ac68dcfc13411978db53a93dd2ebae872e4ae839a6596aa5d76f1a"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
