name = "Unlimited Fabric"
author = "trollham"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc2e1a7365eb911c166d0df8826170667d205bc7e9d3761a554d591bdeec3972"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
